### ISSUE TITLE
Lava doesn't generate under the magma in the ashy shoals biome

### ISSUE THREAD

**Issue by Ookidablobida** [TerraformersMC/Cinderscapes#119]
It's kind of jarring to see the lava end in a completely flat wall of various nether blocks. Also, maybe ash shouldn't accumulate on top of the magma where the lava should be, simply because I think it kind of takes away from the look of it and makes it blend in with the rest of the biome.

**Comment by ghost** [comment]
Like in spectator mode?

**Comment by gniftygnome** [comment]
I think of the magma blocks as a kind of scum that has formed on top of the lava as ash falls on it.  So, I have preserved Trinsdar's change to stop replacing the lava below the magma with netherrack.  Thus, this bug is resolved (except from the POV of anyone who preferred it the other way).

On the topic of ash accumulation, though, IMO it is more consistent with the often hidden dangers of the Nether to have ash on the magma.  The player will be damaged if they wander out onto the magma but it is harder this way to see where that transition is (it is harder to see in general, since covering the magma with ash reduces the light level quite a bit).  So I have actually gone the opposite direction and allowed initial generation to cover the magma when placing the ash top layer...
