### ISSUE TITLE
Ores should be tagged as "#c:ores"

### ISSUE THREAD

**Issue by Dekamir** [TerraformersMC/Cinderscapes#151]
This is to ensure compatibility with other Fabric mods, such as Vein Mining.

Yes, this can be manually added to most configs, but not all.

**Comment by gniftygnome** [comment]
Yeah.  I'll add those.

**Comment by gniftygnome** [comment]
Implemented in 4.0.0-beta.1 for 1.20 and I'll backport them to 1.19.4 in a moment.

**Comment by Dekamir** [comment]
Is there a plan to update backport this to 1.19.2 or is that version is now EOL?

**Comment by gniftygnome** [comment]
There wasn't any plan; aside from the occasional bug fix the 1.19 version is pretty much done, and in many ways the 1.19.4+ versions are quite superior.  Most folks don't realize how hard backporting things from 1.19.4+ to 1.19.2- can be.

That said, it's not particularly difficult in this case, so since you appear to be requesting it, I'll make a backported release.

**Comment by gniftygnome** [comment]
Released as Cinderscapes 3.0.4 for 1.19 - 1.19.2.
