### ISSUE TITLE
AshyShoalsBiome's EmptySurfaceConfig will cause mod compat issues

### ISSUE THREAD

**Issue by TelepathicGrunt** [TerraformersMC/Cinderscapes#25]
Out of all the biome mods, I have never seen anyone ever use the EmptySurfaceConfig at all lol. Except for this mod's AshyShoalsBiome. 

https://github.com/TerraformersMC/Cinderscapes/blob/30bd9f7ec275af15a6664708b9f7a22763bb9254/src/main/java/com/terraformersmc/cinderscapes/biome/AshyShoalsBiome.java#L36

The surfacebuilder really has 2 main purposes. The first being placing top blocks and all and the second is to let other features/mods know what top block to expect from that biome. For example, part of my Wells's surface check code in Repurposed Structures mod does `blockState.isOf(world.getBiome(mutable).getSurfaceConfig().getTopMaterial().getBlock()))` to know when the well is indeed on  a biome's surface block. But with EmptySurfaceConfig, .getTopMaterial() returns null and .getBlock() crashes on that.

I will add checks to my mod to prevent these kinds of crashes but there may be many other mods who won't expect .getTopMaterial() to return null like I did. Perhaps it would be good for AshyShoalsBiome to use a regular surface builder config (even though you wont use any of the blocks in your Surface Builder) just so other mods knows what top block to expect or look for in that biome.

**Comment by ghost** [comment]
At this point the code is unnecessary as we moved most of the logic that used to be in the surface builder elsewhere, so the change ought to be easy.

I would question just generally the viability of using the surface config to determine top materials in the generation of features. Take for example the basalt deltas biome which list Blackstone as its top material, and then Basalt itself as its under material. There's not really all that much blackstone in the basalt deltas because of all of the delta features so it might cause problems when trying to place features based on their bottom block. That could also apply to the Ashy Shoals (although maybe its a bad example because it's modded). If I were to write a surface config for it I would likely list netherrack as the top material when in reality the entire top material eventually get's covered over by ash, and also the biome contains multiple netherrack replacers with the goal of removing most of the netherrack and replacing it with Soul Sand, Soul Soil, and Gravel. In that case I don't believe that knowing the top material would aid in any way to place a feature because the locations that actually only have netherrack would be few and far between.

**Comment by TelepathicGrunt** [comment]
Well consider something like someone making armor that changes to match the general color of the biome? There’s no easy way to get biome colors as the water/grass colors may not apply for the biome. So instead, the mod’s best choice is to check the top layer of the surfacebuilderconfig and use that blocks color. 

Another thought could be a dynamic feature that changes out its blocks for the biome’s surfacebuilderconfig blocks. So in this case, giving the ashey biome’s surface config ash block as top and netherrack as middle and bottom with help with both use cases even when the surface builder doesn’t actually use the config’s blocks directly. 

Just some ideas! Now that I saw this, the dynamically using surfacebuilderconfig blocks to make the feature sounds pretty cool. I might try that and see how it looks for stuff
