### ISSUE TITLE
Enhancement: Add Config File

### ISSUE THREAD

**Issue by JoshMayberry** [TerraformersMC/Cinderscapes#40]
I feel the Ashy Shoals are too common, and would like to modify their appearance ratio (like I can with the other Terraformers mods such as Traverse and Terrestria).
There doesn't seem to be a config file in the configs folder that will allow me to do this though. Could one be added?

**Comment by NeusFear** [comment]
This is already planned for when we do a full release of the mod. Not sure when we'll get around to adding this but yes one will be added in the future.

**Comment by ghost** [comment]
Fair warning because of the way vanilla generates nether biomes it’s not possible to modify the prevalence of a biome in the traditional sense. However, We’re working on a project to overhaul the vanilla nether biome generator. That would allow for that capability, but obviously this is more difficult than simply adding a config which is why it’s taking a lot longer.

**Comment by JoshMayberry** [comment]
Makes sense. I hadn't realized Cinderscapes was still under development. :) Good luck! You guys are doing awesome!
