### ISSUE TITLE
Luminescent groves are way too easy.

### ISSUE THREAD

**Issue by Angular-Angel** [TerraformersMC/Cinderscapes#79]
They have tons of light source blocks, almost all of which can be harvested by hand, and basically no enemies - hoglins and piglins don;t seem to spawn in them, nor any other hostile mob unless there's a blaze spawner. I would suggest cutting down on the light sources - no more boulders of shroomlights on the ground and fewer in umbral mushrooms, make umbral flesh stop glowing when broken unless you use a shears, maybe reduce light from small umbral mushrooms. Add piglin and hoglin spawns same as nylium biomes, and maybe some other danger? Maybe some of the light sources will do damage to you if you get too close, or if there are too many in a small area?

**Comment by saltyseadoggo** [comment]
This is an interesting one. In the code, the only things that can spawn in Luminous Groves are Endermen, which would put their danger levels on par with the Warped Forests, _except_ the light levels prevent the Endermen from spawning. Wandering around one, the light levels are often too high even for zombified Piglins, Piglins or Hoglins, who spawn at light level eleven or lower as opposed to seven, to spawn. If this is deemed an issue, perhaps whatever allows Endermen to spawn in differing light levels in the End as compared to the overworld and Nether could be leveraged to allow other mobs to spawn in the Luminous Grove regardless of light levels?
In terms of what mobs spawn in the Grove, I think they could do with some distancing from the Warped Forests, whose whole niche is their exclusive spawning of Endermen. I'm not sure what would fit in such an environment, truthfully...

Edit! I thought that perhaps Cave Spiders could be a good fit for the Luminous Grove. They would provide Nether-only players a source of spider eyes and their aggregate fermented spider eyes, and they visually fit the biome's colour scheme~

**Comment by ghost** [comment]
The luminous grove is intended to be kind of a safe haven for players. It's supposed to be kind of like the warped forest but even more habitable. For that reason it's pretty much intentional that it's really really easy. That being said I get your point, in terms of life in the biome there really isn't much because there's no spawns. We have plans in the future to make a mob related mod that might be able to address giving this biome some more life, but right now there's nothing set in stone. I'm gonna go ahead and close this because it's less of an issue and more intentional game design.
