### ISSUE TITLE
Incompatibility with Curios

### ISSUE THREAD

**Issue by Zentheon** [TerraformersMC/Cinderscapes#95]
When both the Curios API and Cinderscapes are loaded at once, the Creative menu never shows any of the vanilla blocks or items. 

I doubt it would give any valuable info, but the console log is the only resource I can give (Don't mind the missing structure spam, been testing a lot of mods):
[latest.log](https://github.com/TerraformersMC/Cinderscapes/files/5435796/latest.log)

**Comment by Zentheon** [comment]
It looks like this actually happens with quite a few different mods, and only when Cinderscapes is loaded. Working on a list of all the ones that do this, but it's starting to look like it could be linked to some sort of GUI library. Just a wild guess

**Comment by dandin87** [comment]
You need to have the latest https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3089804 CCA version. Seen this quite a bit now. We had it with AoF3 Dev pack. Doesn't make much sense since Cinderscapes is not using CCA but the pack had 2.6 and once we added Cinderscapes the creative inventory had no Vanilla items. Updating CCA to 2.7+ fixed the issue.

**Comment by ghost** [comment]
Yeah this is kind of a really weird issue. I'm not entirely sure what's going on. Because it happens with multiple mods, and the only way Cinderscapes ever interacts with Item groups is through Fabric API (and it never touches custom rendering), it is my belief that this is an issue with Fabric API itself. In the meantime updating to the newest versions of projects seems to be fixing it, but I've also opened an issue on the Fabric API repository (https://github.com/FabricMC/fabric/issues/1132) to track this issue in more depth. It would be much appreciated if we moved discussion there so we can figure out exactly how many mods this affects and try to find a pattern between them.
